spring.datasource.url=jdbc:h2:mem:tododb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# JWT properties
todo.app.jwtSecret=todoSecretKey123456789012345678901234567890123456789012345678901234567890
todo.app.jwtExpirationMs=86400000
